"""add disposition column in pvb table

Revision ID: 7f62697feffc
Revises: c930c0dbcb1a
Create Date: 2025-12-18 09:55:58.087232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f62697feffc'
down_revision: Union[str, Sequence[str], None] = 'c930c0dbcb1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pvb_violations', sa.Column('disposition', sa.Enum('PAID', 'REDUCED', 'DISMISSED', name='pvbdisposition'), nullable=True))
    op.add_column('pvb_violations', sa.Column('disposition_change_date', sa.Date(), nullable=True))
    op.add_column('pvb_violations', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pvb_violations', 'note')
    op.drop_column('pvb_violations', 'disposition_change_date')
    op.drop_column('pvb_violations', 'disposition')
    # ### end Alembic commands ###
