"""reduce_to column added

Revision ID: 8f23375d69ec
Revises: 7af4a5117614
Create Date: 2025-12-23 05:18:57.459675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f23375d69ec'
down_revision: Union[str, Sequence[str], None] = '7af4a5117614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pvb_violations', sa.Column('reduce_to', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pvb_violations', 'reduce_to')
    # ### end Alembic commands ###
