"""add columns in tlc

Revision ID: c6a6e5273d74
Revises: abab11b9bf99
Create Date: 2025-12-15 11:19:28.056329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c6a6e5273d74'
down_revision: Union[str, Sequence[str], None] = 'abab11b9bf99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tlc_violations', sa.Column('ea_reason', sa.Text(), nullable=True, comment='Reason for EA violation type'))
    op.add_column('tlc_violations', sa.Column('disposition_change_date', sa.Date(), nullable=True))
    op.alter_column('tlc_violations', 'violation_type',
               existing_type=mysql.ENUM('FI', 'FN', 'RF', 'EA'),
               type_=sa.String(length=255),
               comment='Type of TLC violation.',
               existing_nullable=False)
    op.drop_column('tlc_violations', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tlc_violations', sa.Column('description', mysql.TEXT(), nullable=True, comment='Required only if type is FN.'))
    op.alter_column('tlc_violations', 'violation_type',
               existing_type=sa.String(length=255),
               type_=mysql.ENUM('FI', 'FN', 'RF', 'EA'),
               comment=None,
               existing_comment='Type of TLC violation.',
               existing_nullable=False)
    op.drop_column('tlc_violations', 'disposition_change_date')
    op.drop_column('tlc_violations', 'ea_reason')
    # ### end Alembic commands ###
