"""increase length driver role

Revision ID: c930c0dbcb1a
Revises: e75520de272f
Create Date: 2025-12-17 08:35:02.471167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c930c0dbcb1a'
down_revision: Union[str, Sequence[str], None] = 'e75520de272f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lease_drivers', 'driver_role',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=30),
               existing_comment='Driver role will include DL,NL, X,DX, NX',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lease_drivers', 'driver_role',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=10),
               existing_comment='Driver role will include DL,NL, X,DX, NX',
               existing_nullable=True)
    # ### end Alembic commands ###
