"""add current_location column in vehicles tables

Revision ID: e75520de272f
Revises: abab11b9bf99
Create Date: 2025-12-16 10:57:06.454630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e75520de272f'
down_revision: Union[str, Sequence[str], None] = 'abab11b9bf99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_insurance',
    sa.Column('id', sa.Integer(), nullable=False, comment='Primary Key for Vehicle Insurance'),
    sa.Column('vehicle_id', sa.Integer(), nullable=False, comment='Foreign Key to Vehicle table'),
    sa.Column('insurance_type', sa.String(length=255), nullable=True, comment='Type of insurance'),
    sa.Column('insurance_number', sa.String(length=255), nullable=True, comment='Insurance number of the vehicle'),
    sa.Column('insurance_start_date', sa.Date(), nullable=True, comment='Insurance start date of the vehicle'),
    sa.Column('insurance_end_date', sa.Date(), nullable=True, comment='Insurance end date of the vehicle'),
    sa.Column('amount', sa.Float(), nullable=True, comment='Insurance amount'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Insurance Status'),
    sa.Column('is_archived', sa.Boolean(), nullable=True, comment='Flag indicating if the record is archived'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Flag to keep track of record is active or not'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='User who created this record'),
    sa.Column('modified_by', sa.Integer(), nullable=True, comment='User who last modified this record'),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Timestamp when this record was created'),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when this record was last updated'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('vehicles', sa.Column('current_location', sa.String(length=255), nullable=True, comment='Current location of the vehicle'))
    op.add_column('vehicles', sa.Column('location_changed_date', sa.Date(), nullable=True, comment='Date when the location was last changed'))
    op.add_column('vehicles', sa.Column('comment_for_location_change', sa.Text(), nullable=True, comment='Comment for the location change'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'comment_for_location_change')
    op.drop_column('vehicles', 'location_changed_date')
    op.drop_column('vehicles', 'current_location')
    op.drop_table('vehicle_insurance')
    # ### end Alembic commands ###
