"""specific_location column added in vehicle table

Revision ID: ee935892a1e9
Revises: c930c0dbcb1a
Create Date: 2025-12-19 08:32:39.704870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee935892a1e9'
down_revision: Union[str, Sequence[str], None] = 'c930c0dbcb1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('specific_location', sa.String(length=255), nullable=True, comment='Specific location of the vehicle'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'specific_location')
    # ### end Alembic commands ###
